default: &default
  adapter: postgresql
  encoding: unicode

  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
development:
  <<: *default
  adapter: postgresql
  database: <%= ENV["database.db_name"] %>
  username: <%= ENV["database.username"] %>
  password: <%= ENV["database.password"] %>
  host: <%= ENV["database.host"] %>
  port: <%= ENV["database.port"] %>
  pool: 5
